### PR TITLE
remove stage-1

### PR DESCRIPTION
**Pull request by graingert**
People can use stage-1 directly from babel. There's no changes between the stage-1 provided by this package and the official stage-1.

When rules migrate out of stage-0 and into ES they can be included directly in modern-browsers.

### CODE REVIEW

**Comment by christophehurpeau** [comment]
You can use stage-1 directly from `babel-preset-stage-1`. However, the idea was to not transform some features already implemented in browsers. Currently, there is no change, but in the near future the exponentiation operator will be implemented (already in Edge 14 and Chrome 52, waiting for Firefox). The config file will allow to remove the transform in this package, with no change in the dependencies.
We could create another package, like `babel-preset-modern-browsers-stage-1` maybe it's a better idea ?

**Comment by graingert** [comment]
When that happens I expect babel will move the rule out of stage-3 and into
an es2015 preset.

**Comment by graingert** [comment]
@christophehurpeau this is actually what happened, when the features graduate staging they get removed and moved into the latest es20XX preset: https://github.com/babel/babel/releases/tag/v6.11.0

**Comment by christophehurpeau** [comment]
Closed: removed stage-1 from this repository.

You can either use [babel-preset-stage-1](https://www.npmjs.com/package/babel-preset-stage-1) or [babel-preset-modern-browsers-stage-1](https://www.npmjs.com/package/babel-preset-modern-browsers-stage-1) or

**Pull request closed without merging**
